# algaetax; Config File
# General settings
general:
  input_data: "input_data/example_file.xlsx" # Path to input Excel file (e.g. input_data/example_file.xlsx)
  output_dir: "results_algaetax" # Folder to save results (e.g. results_algaetax/)
  taxa_column_letter: "D" # Excel column with taxonomy names (e.g. A, B, C, D)
  header_row: 0 # 0 = first row has headers, None = no header row
  backup_file: true # Create backup of input file (true/false)
  export_not_found_taxa_list: true # Export list of taxa where ALL used databases returned "Not found" (file: taxa_not_found.csv)

# Taxa filter settings
filter:
  # Terms to ignore in species names (e.g. generic or uncertain labels)
  blacklist: ["sp", "sp.", "spec", "spec.", "cf", "cf.", "nr", "nr.", "gran", sonst", "sonst.", "Komplex", "komplex", "complex", "unb"]

# Databases to use
database:
  NCBI: false # Enable NCBI (e.g. true or false)
  PR2: false # Enable local PR2 (e.g. true)
  ALGB: false # Enable AlgaeBase (e.g. false if no key)

# Paths to local database files
database_path:
  db_pr2: "database/pr2_version_5.1.0_taxonomy.xlsx" # Path to PR2 file (e.g. database/pr2_v5.xlsx)

# NCBI API settings
db_ncbi:
  ncbi_email: "anonymous@ncbi.com" # Email for NCBI queries (default: anonymous@ncbi.com, e.g. you@example.com)
  api_key: "" # Optional key to speed up requests (e.g. abc123xyz)

# AlgaeBase API settings
db_algaebase:
  api_key: "" # API key for AlgaeBase (e.g. abc123xyz)
  api_url: "https://api.algaebase.org/v1.3/species" # API URL (see docs: algaebase.org/api/)
