# algaetax; configuration file: config.yaml

# General settings
general:
  input_data: "input_data/algaetax_test" # Path to input Excel file (e.g. input_data/example_file.xlsx)
  output_dir: "results_algaetax" # Folder to save results (default: results_algaetax/)
  taxa_column_number: 1 # 1-based index: 1 = column A, 27 = column AA
  header_row: 1 # Excel header row (1 = first row); set to false if the file has no header
  backup_config: true # # Copy the config.yaml file to the output directory for reference (default=true)
  backup_input: true # Backup of the input Excel file before processing (true/false)
  export_not_found_taxa_list: true # Export list of taxa where ALL used databases returned "Not found" (file: taxa_not_found.csv)

  # Optional: defines which column in the input file contains unique sample or sequence IDs.
  # These IDs will be added to the output for easier tracking of each taxon entry.
  id_column_number: false  # Use 1-based index (e.g., 1 = column A); set to false to disable

# Taxa filter settings
filter:
  blacklist_file: blacklist.txt # Path to text file with terms to ignore in species names
  backup_blacklist: true # Create a backup of the blacklist in {output_dir}/backups (default=true)

# Databases to use
database:
  NCBI: true # Use NCBI Database
  PR2: true # Use local PR2 Database
  ALGB: true # Use AlgaeBase Database (requires API key!)

# Paths to local database files
database_path:
  db_pr2: "database/pr2_version_5.1.0_taxonomy.xlsx" # Path to PR2 file (e.g. database/pr2_v5.xlsx)

# NCBI API settings
db_ncbi:
  api_key: "" # Optional key to speed up requests (e.g. abc123xyz)
  ncbi_email: "anonymous@ncbi.com" # Email for NCBI queries (default: anonymous@ncbi.com, e.g. name@example.com)

# AlgaeBase API settings
db_algaebase:
  api_key: "" # API key for AlgaeBase (e.g. abc123xyz)
  api_url: "https://api.algaebase.org/v1.3/species" # API URL (see docs: algaebase.org/api/)
